# Generated by Django 5.0.1 on 2024-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0002_remove_size_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
