# Generated by Django 5.0.1 on 2024-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0003_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('masage', models.TextField(verbose_name='Сообщение')),
                ('number', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
    ]
