# Generated by Django 5.0.1 on 2024-02-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
